version: '3.9'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - wordpress

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    environment:
      WORDPRESS_DB_HOST: postgres
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: app_db
    ports:
      - "8080:80"
    depends_on:
      - postgres
